### ISSUE TITLE
Add and implement Roles model

### ISSUE THREAD

**Issue by ovan001** [ovan001/vacancy#3]
Roles allows to control how users will behave in the system and where they will have access to.
E.g., administrator, moderator, employer, freelancer etc...

**Comment by kefzce** [comment]
**Should Be closed** [Added make:auth scaffoldAdded backpack(base, crud, permissionmanager, menucrud, newscrud) and…](https://github.com/ovan001/vacancy/commit/db7949144ca544201ed2444fc15f9eaa42f50ecb)
